[2025-06-05T23:29:10.590-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test1.get_info scheduled__2025-06-05T02:28:40.519682+00:00 [queued]>
[2025-06-05T23:29:10.597-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test1.get_info scheduled__2025-06-05T02:28:40.519682+00:00 [queued]>
[2025-06-05T23:29:10.598-0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-06-05T23:29:10.703-0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_info> on 2025-06-05 02:28:40.519682+00:00
[2025-06-05T23:29:10.706-0300] {standard_task_runner.py:57} INFO - Started process 37394 to run task
[2025-06-05T23:29:10.708-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'test1', 'get_info', 'scheduled__2025-06-05T02:28:40.519682+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp7sll95_p']
[2025-06-05T23:29:10.708-0300] {standard_task_runner.py:85} INFO - Job 5: Subtask get_info
[2025-06-05T23:29:10.839-0300] {task_command.py:410} INFO - Running <TaskInstance: test1.get_info scheduled__2025-06-05T02:28:40.519682+00:00 [running]> on host alex-MS-7D46
[2025-06-05T23:29:13.175-0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='test1' AIRFLOW_CTX_TASK_ID='get_info' AIRFLOW_CTX_EXECUTION_DATE='2025-06-05T02:28:40.519682+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-05T02:28:40.519682+00:00'
[2025-06-05T23:29:13.175-0300] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alex/mlopszoomcamp/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/alex/mlopszoomcamp/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/alex/Homeworks/HW3/dags/test.py", line 34, in get_info
    df = pd.read_parquet("data/yellow_tripdata_2023-03.parquet")
  File "/home/alex/mlopszoomcamp/lib/python3.10/site-packages/pandas/io/parquet.py", line 653, in read_parquet
    impl = get_engine(engine)
  File "/home/alex/mlopszoomcamp/lib/python3.10/site-packages/pandas/io/parquet.py", line 68, in get_engine
    raise ImportError(
ImportError: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - Missing optional dependency 'pyarrow'. pyarrow is required for parquet support. Use pip or conda to install pyarrow.
 - Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.
[2025-06-05T23:29:13.181-0300] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=test1, task_id=get_info, execution_date=20250605T022840, start_date=20250606T022910, end_date=20250606T022913
[2025-06-05T23:29:13.375-0300] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task get_info (Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - Missing optional dependency 'pyarrow'. pyarrow is required for parquet support. Use pip or conda to install pyarrow.
 - Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.; 37394)
[2025-06-05T23:29:13.412-0300] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-06-05T23:29:13.627-0300] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
