[2025-06-06T22:05:43.761-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: taxi_pipeline.transform_data manual__2025-06-07T00:41:19.254969+00:00 [queued]>
[2025-06-06T22:05:43.764-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: taxi_pipeline.transform_data manual__2025-06-07T00:41:19.254969+00:00 [queued]>
[2025-06-06T22:05:43.764-0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-06-06T22:05:43.860-0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): transform_data> on 2025-06-07 00:41:19.254969+00:00
[2025-06-06T22:05:43.865-0300] {standard_task_runner.py:57} INFO - Started process 55639 to run task
[2025-06-06T22:05:43.867-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'taxi_pipeline', 'transform_data', 'manual__2025-06-07T00:41:19.254969+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/taxi_dag.py', '--cfg-path', '/tmp/tmpifdobgo1']
[2025-06-06T22:05:43.867-0300] {standard_task_runner.py:85} INFO - Job 24: Subtask transform_data
[2025-06-06T22:05:43.999-0300] {task_command.py:410} INFO - Running <TaskInstance: taxi_pipeline.transform_data manual__2025-06-07T00:41:19.254969+00:00 [running]> on host alex-MS-7D46
[2025-06-06T22:05:44.190-0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='taxi_pipeline' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-06-07T00:41:19.254969+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-07T00:41:19.254969+00:00'
[2025-06-06T22:05:56.368-0300] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alex/mlopszoomcamp/lib/python3.10/site-packages/pandas/core/ops/array_ops.py", line 218, in _na_arithmetic_op
    result = func(left, right)
  File "/home/alex/mlopszoomcamp/lib/python3.10/site-packages/pandas/core/computation/expressions.py", line 242, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]
  File "/home/alex/mlopszoomcamp/lib/python3.10/site-packages/pandas/core/computation/expressions.py", line 73, in _evaluate_standard
    return op(a, b)
TypeError: unsupported operand type(s) for -: 'str' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alex/mlopszoomcamp/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/alex/mlopszoomcamp/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/alex/Homeworks/HW3/dags/taxi_dag.py", line 48, in transform_data
    df = pd.read_sql('SELECT * FROM yellow_march23', con=conn)
  File "/home/alex/mlopszoomcamp/lib/python3.10/site-packages/pandas/core/ops/common.py", line 76, in new_method
    return method(self, other)
  File "/home/alex/mlopszoomcamp/lib/python3.10/site-packages/pandas/core/arraylike.py", line 194, in __sub__
    return self._arith_method(other, operator.sub)
  File "/home/alex/mlopszoomcamp/lib/python3.10/site-packages/pandas/core/series.py", line 6146, in _arith_method
    return base.IndexOpsMixin._arith_method(self, other, op)
  File "/home/alex/mlopszoomcamp/lib/python3.10/site-packages/pandas/core/base.py", line 1391, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
  File "/home/alex/mlopszoomcamp/lib/python3.10/site-packages/pandas/core/ops/array_ops.py", line 283, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)  # type: ignore[arg-type]
  File "/home/alex/mlopszoomcamp/lib/python3.10/site-packages/pandas/core/ops/array_ops.py", line 227, in _na_arithmetic_op
    result = _masked_arith_op(left, right, op)
  File "/home/alex/mlopszoomcamp/lib/python3.10/site-packages/pandas/core/ops/array_ops.py", line 163, in _masked_arith_op
    result[mask] = op(xrav[mask], yrav[mask])
TypeError: unsupported operand type(s) for -: 'str' and 'str'
[2025-06-06T22:05:56.406-0300] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=taxi_pipeline, task_id=transform_data, execution_date=20250607T004119, start_date=20250607T010543, end_date=20250607T010556
[2025-06-06T22:05:56.517-0300] {standard_task_runner.py:104} ERROR - Failed to execute job 24 for task transform_data (unsupported operand type(s) for -: 'str' and 'str'; 55639)
[2025-06-06T22:05:56.657-0300] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-06-06T22:05:56.664-0300] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
